name: cylc8
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pyzmq
  - python-jose
  - colorama
  - jinja2
  - pytest
  - pycodestyle
  - coverage
  - pytest-cov
  - pip:
    - empy
