name: Release stage 1 - create release PR (Cylc 8+ only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (PEP 440 compliant e.g., 8.12.4, 8.0a2 etc)
        required: true
      branch:
        description: The branch to open the PR against
        required: false
        default: 'master'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Sanitise workflow inputs # Should be 1st step
        uses: cylc/release-actions/stage-1/sanitize-inputs@v1

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_REF }}
          fetch-depth: 0  # need to fetch all commits to check contributors

      - name: Check CONTRIBUTING.md
        uses: cylc/release-actions/check-shortlog@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # return to 3.x once compatible with 3.10+ (pyuv)
          python-version: '3.9'

      - name: Create & checkout PR branch
        uses: cylc/release-actions/stage-1/checkout-pr-branch@v1

      - name: Set the package version
        uses: cylc/release-actions/stage-1/set-python-package-version@v1
        with:
          init-file: 'cylc/flow/__init__.py'
          pypi-package-name: 'cylc-flow'

      - name: Update "released on" date in changelog
        continue-on-error: true
        uses: cylc/release-actions/stage-1/update-changelog-release-date@v1
        with:
          changelog-file: 'CHANGES.md'

      - name: Test build
        uses: cylc/release-actions/build-python-package@v1

      - name: Create pull request
        uses: cylc/release-actions/stage-1/create-release-pr@v1
        with:
          test-workflows: test_fast.yml, test_functional.yml, bash.yml, test_manylinux.yml, test_conda-build.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
